before_script:
  - bash docker_install.sh

analyse:
  image: edbizarro/gitlab-ci-pipeline-php:7.1
  script:
    - composer require --dev phpstan/phpstan
    - vendor/bin/phpstan analyse src tests

test:7.2:
    image: edbizarro/gitlab-ci-pipeline-php:7.2
    stage: test
    script:
      - make build
      - make test

test:7.1:
    image: edbizarro/gitlab-ci-pipeline-php:7.1
    stage: test
    script:
      - make build
      - make test

test:7.0:
    image: edbizarro/gitlab-ci-pipeline-php:7.0
    stage: test
    script:
      - make build
      - make test