before_script:
  - bash docker_install.sh

analyse:
    stage: analyse
    script:
      - docker run --rm -v $(pwd):/app phpstan/phpstan analyse /app/src

test:7.2:
    image: edbizarro/gitlab-ci-pipeline-php:7.2
    stage: test
    script:
      - make build
      - make test

test:7.1:
    image: edbizarro/gitlab-ci-pipeline-php:7.1
    stage: test
    script:
      - make build
      - make test

test:7.0:
    image: edbizarro/gitlab-ci-pipeline-php:7.0
    stage: test
    script:
      - make build
      - make test