before_script:
  - bash docker_install.sh

analyse:
  image: phpstan/phpstan
  before_script: ~
  script:
    - analyse /app/src --level=7s

test:7.2:
    image: edbizarro/gitlab-ci-pipeline-php:7.2
    stage: test
    script:
      - make build
      - make test

test:7.1:
    image: edbizarro/gitlab-ci-pipeline-php:7.1
    stage: test
    script:
      - make build
      - make test

test:7.0:
    image: edbizarro/gitlab-ci-pipeline-php:7.0
    stage: test
    script:
      - make build
      - make test