analyse:
  image: edbizarro/gitlab-ci-pipeline-php:7.1
  allow_failure: true
  script:
    - composer install
    - composer require --dev phpstan/phpstan
    - vendor/bin/phpstan analyse src --level=7

test:7.2:
    image: edbizarro/gitlab-ci-pipeline-php:7.2
    stage: test
    script:
      - composer install
      - make test

test:7.1:
    image: edbizarro/gitlab-ci-pipeline-php:7.1
    stage: test
    script:
      - composer install
      - make test

test:7.0:
    image: edbizarro/gitlab-ci-pipeline-php:7.0
    stage: test
    script:
      - composer install
      - make test