info:
paths:
  /books:
    get:
      operationId: getBooks
      responses:
        '200':
          description: Fetch list of books
          content:
            application/json:
              schema:
                type: object
                required:
                  - name
                properties:
                  name:
                    type: string
                    nullable: false
                    example: "Vulcan lives"
                  tag:
                    type: string
                    example: "foo"
            application/xml:
              schema:
                type: object
                required:
                  - count
                properties:
                  count:
                    type: integer
openapi: 3.0.0